openapi: 3.1.0
info:
  title: 最低賃金API
  description: |
    日本の最低賃金を取得するAPI

    追加/変更要望, 不具合報告は[GitHub](https://github.com/LruLab/minimum-wage-api)まで
  contact: 
    url: https://github.com/LruLab/minimum-wage-api
  version: 1.0.0
servers:
  - url: https://minimum-wage-api.vercel.app/
paths:
  /:
    get:
      operationId: getWage
      summary: 最低賃金取得
      parameters:
        - in: query
          name: prefecture
          description: |
            指定された都道府県の最低賃金情報を返却する  
            未指定の場合は全ての都道府県の最低賃金情報を返却する

            クエリとしては以下のいづれかを指定できる  
            - 正式な都道府県名
              - ex. 東京都, 大阪府, 沖縄県
            - 「都」「府」「県」を除いた都道府県名
              - ex. 東京, 大阪, 沖縄
            - 都道府県の英名
              - ex. Tokyo, Osaka, Okinawa

          schema:
            type: string
            example: 東京
        - in: query
          name: date
          description: |
            指定された日付時点での最低賃金情報を返却する  
            未指定の場合はリクエスト時点での最低賃金情報を返却する

            2002年10月頃以前のデータは含まれていないため, それ以前の日付を指定した場合はレスポンスは空配列となる
          schema:
            type: string
            format: date
            pattern: '^\d{4}-\d{2}-\d{2}$'
            example: '2023-10-01'
      responses:
        200:
          description: 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/minimum_wage'
components:
  schemas:
    minimum_wage:
      description: 最低賃金情報
      type: object
      properties:
        prefecture:
          description: 都道府県名
          type: string
          enum:
            - 北海道
            - 青森
            - 岩手
            - 宮城
            - 秋田
            - 山形
            - 福島
            - 茨城
            - 栃木
            - 群馬
            - 埼玉
            - 千葉
            - 東京
            - 神奈川
            - 新潟
            - 富山
            - 石川
            - 福井
            - 山梨
            - 長野
            - 岐阜
            - 静岡
            - 愛知
            - 三重
            - 滋賀
            - 京都
            - 大阪
            - 兵庫
            - 奈良
            - 和歌山
            - 鳥取
            - 島根
            - 岡山
            - 広島
            - 山口
            - 徳島
            - 香川
            - 愛媛
            - 高知
            - 福岡
            - 佐賀
            - 長崎
            - 熊本
            - 大分
            - 宮崎
            - 鹿児島
            - 沖縄
          example: 東京
        date_of_issue:
          description: 発効日 (該当賃金の適用開始日)
          type: string
          format: date
          pattern: '^\d{4}-\d{2}-\d{2}$'
          example: '2023-10-01'
        wage:
          description: 最低賃金
          type: integer
          example: 1113
